const localize = require("nativescript-localize");

exports.interventionDetails = [
{
  id: 0,
  shortname: 'GLANCE_NOTIFICATION',
  name: localize("interventions.data.0.name"),
  icon: 'res://ic_eye', 
  functionality: localize("interventions.data.0.functionality"), 
  description: localize("interventions.data.0.description"), 
  target: 'phone', 
  level: 'easy',
  summary: localize("interventions.data.0.summary"),
  style: 'notification'
}, {
  id: 1,
  shortname: 'UNLOCK_TOAST',
  name: localize("interventions.data.1.name"), 
  icon: 'res://ic_smile', 
  functionality: localize("interventions.data.1.functionality"), 
  description: localize("interventions.data.1.description"), 
  target: 'phone', 
  level: 'easy',
  summary: localize("interventions.data.1.summary"),
  style: 'toast'
}, {
  id: 2,
  shortname: 'UNLOCK_NOTIFICATION',
  name: localize("interventions.data.2.name"), 
  icon: 'res://ic_hand', 
  functionality: localize("interventions.data.2.functionality"), 
  description: localize("interventions.data.2.description"), 
  target: 'phone', 
  level: 'easy',
  summary: localize("interventions.data.2.summary"),
  style: 'notification'
}, {
  id: 3,
  shortname: 'USAGE_TOAST',
  name: localize("interventions.data.3.name"), 
  icon: 'res://ic_clipboard', 
  functionality: localize("interventions.data.3.functionality"), 
  description: localize("interventions.data.3.description"), 
  target: 'app', 
  level: 'easy',
  summary: localize("interventions.data.3.summary"),
  style: 'toast'
}, {
  id: 4,
  shortname: 'USAGE_NOTIFICATION',
  name: localize("interventions.data.4.name"), 
  icon: 'res://ic_alert', 
  functionality: localize("interventions.data.4.functionality"), 
  description: localize("interventions.data.4.description"), 
  target: 'app', 
  level: 'easy',
  summary: localize("interventions.data.4.summary"),
  style: 'notification'
}, {
  id: 5,
  shortname: 'DURATION_TOAST',
  name: localize("interventions.data.5.name"), 
  icon: 'res://ic_plane', 
  functionality: localize("interventions.data.5.functionality"), 
  description: localize("interventions.data.5.description"), 
  target: 'duration', 
  level: 'easy',
  summary: localize("interventions.data.5.summary"),
  style: 'toast'
}, {
  id: 6,
  shortname: 'DURATION_NOTIFICATION',
  name: localize("interventions.data.6.name"), 
  icon: 'res://ic_clock', 
  functionality: localize("interventions.data.6.functionality"), 
  description: localize("interventions.data.6.description"), 
  target: 'duration',
  level: 'easy',
  summary: localize("interventions.data.6.summary"),
  style: 'notification'
}, {
  id: 7,
  shortname: 'VISIT_TOAST',
  name: localize("interventions.data.7.name"), 
  icon: 'res://ic_history', 
  functionality: localize("interventions.data.7.functionality"), 
  description: localize("interventions.data.7.description"), 
  target: 'app', 
  level: 'easy',
  summary: localize("interventions.data.7.summary"),
  style: 'toast'
}, {
  id: 8,
  shortname: 'VISIT_NOTIFICATION',
  name: localize("interventions.data.8.name"), 
  icon: 'res://ic_repeat', 
  functionality: localize("interventions.data.8.functionality"), 
  description: localize("interventions.data.8.description"), 
  target: 'app', 
  level: 'easy',
  summary: localize("interventions.data.8.summary"),
  style: 'notification'
}, {
  id: 9,
  shortname: 'FULL_SCREEN_OVERLAY',
  name: localize("interventions.data.9.name"), 
  icon: 'res://ic_key', 
  functionality: localize("interventions.data.9.functionality"), 
  description: localize("interventions.data.9.description"), 
  target: 'app', 
  level: 'medium',
  summary: localize("interventions.data.9.summary"),
  style: 'overlay'
}, {
  id: 10,
  shortname: 'COUNTUP_TIMER_OVERLAY',
  name: localize("interventions.data.10.name"), 
  icon: 'res://ic_timer', 
  functionality: localize("interventions.data.10.functionality"), 
  description: localize("interventions.data.10.description"), 
  target: 'app', 
  level: 'medium',
  summary: localize("interventions.data.10.summary"),
  style: 'overlay'
}, {
  id: 11,
  shortname: 'COUNTDOWN_TIMER_OVERLAY',
  name: localize("interventions.data.11.name"), 
  icon: 'res://ic_hourglass', 
  functionality: localize("interventions.data.11.functionality"), 
  description: localize("interventions.data.11.description"), 
  target: 'app', 
  level: 'hard',
  summary: localize("interventions.data.11.summary"),
  style: 'overlay'
}, {
  id: 12,
  shortname: 'UNLOCK_DIALOG',
  name: localize("interventions.data.12.name"), 
  icon: 'res://ic_shield', 
  functionality: localize("interventions.data.12.functionality"), 
  description: localize("interventions.data.12.description"), 
  target: 'phone', 
  level: 'medium',
  summary: localize("interventions.data.12.summary"),
  style: 'dialog'
}, {
  id: 13,
  shortname: 'USAGE_DIALOG',
  name: localize("interventions.data.13.name"), 
  icon: 'res://ic_infinity', 
  functionality: localize("interventions.data.13.functionality"), 
  description: localize("interventions.data.13.description"), 
  target: 'app', 
  level: 'medium',
  summary: localize("interventions.data.13.summary"),
  style: 'dialog'
}, {
  id: 14,
  shortname: 'DURATION_DIALOG',
  name: localize("interventions.data.14.name"), 
  icon: 'res://ic_book', 
  functionality: localize("interventions.data.14.functionality"), 
  description: localize("interventions.data.14.description"), 
  target: 'duration', 
  level: 'medium',
  summary: localize("interventions.data.14.summary"),
  style: 'dialog'
}, {
  id: 15,
  shortname: 'VISIT_DIALOG',
  name: localize("interventions.data.15.name"), 
  icon: 'res://ic_rowing', 
  functionality: localize("interventions.data.15.functionality"), 
  description: localize("interventions.data.15.description"), 
  target: 'app', 
  level: 'medium',
  summary: localize("interventions.data.15.summary"),
  style: 'dialog'
}, {
  id: 16,
  shortname: 'DIMMER_OVERLAY',
  name: localize("interventions.data.16.name"), 
  icon: 'res://ic_lightbulb', 
  functionality: localize("interventions.data.16.functionality"), 
  description: localize("interventions.data.16.description"), 
  target: 'app', 
  level: 'hard',
  summary: localize("interventions.data.16.summary"),
  style: 'overlay'
}, {
  id: 17,
  shortname: 'PHONE_USAGE_TOAST',
  name: localize("interventions.data.17.name"), 
  icon: 'res://ic_search', 
  functionality: localize("interventions.data.17.functionality"), 
  description: localize("interventions.data.17.description"), 
  target: 'phone', 
  level: 'easy',
  summary: localize("interventions.data.17.summary"),
  style: 'toast'
}, {
  id: 18,
  shortname: 'PHONE_USAGE_NOTIFICATION',
  name: localize("interventions.data.18.name"), 
  icon: 'res://ic_moon', 
  functionality: localize("interventions.data.18.functionality"), 
  description: localize("interventions.data.18.description"), 
  target: 'phone', 
  level: 'easy',
  summary: localize("interventions.data.18.summary"),
  style: 'notification'
}, {
  id: 19,
  shortname: 'PHONE_USAGE_DIALOG',
  name: localize("interventions.data.19.name"), 
  icon: 'res://ic_phone', 
  functionality: localize("interventions.data.19.functionality"), 
  description: localize("interventions.data.19.description"), 
  target: 'phone', 
  level: 'easy',
  summary: localize("interventions.data.19.summary"),
  style: 'dialog'
}, {
  id: 20,
  shortname: 'APPLICATION_SLIDER',
  name: localize("interventions.data.20.name"), 
  icon: 'res://ic_slider', 
  functionality: localize("interventions.data.20.functionality"), 
  description: localize("interventions.data.20.description"), 
  target: 'app', 
  level: 'hard',
  summary: localize("interventions.data.20.summary"),
  style: 'dialog'
}, {
  id: 21,
  shortname: 'INTERSTITIAL',
  name: localize("interventions.data.21.name"), 
  icon: 'res://ic_pause', 
  functionality: localize("interventions.data.21.functionality"), 
  description: localize("interventions.data.21.description"), 
  target: 'app', 
  level: 'hard',
  summary: localize("interventions.data.21.summary"),
  style: 'overlay'
}, {
  id: 22,
  shortname: 'POSITIVE_TOAST',
  name: localize("interventions.data.22.name"), 
  icon: 'res://ic_heart', 
  functionality: localize("interventions.data.22.functionality"), 
  description: localize("interventions.data.22.description"), 
  target: 'app', 
  level: 'medium',
  summary: localize("interventions.data.22.summary"),
  style: 'toast'
}, {
  id: 23,
  shortname: 'POSITIVE_FULL_SCREEN_OVERLAY',
  name: localize("interventions.data.23.name"), 
  icon: 'res://ic_input_white', 
  functionality: localize("interventions.data.23.functionality"), 
  description: localize("interventions.data.23.description"), 
  target: 'app', 
  level: 'medium',
  summary: localize("interventions.data.23.summary"),
  style: 'overlay'
}, {
  id: 24,
  shortname: 'QUOTE_NOTIFICATION',
  name: localize("interventions.data.24.name"), 
  icon: 'res://ic_phone', 
  functionality: localize("interventions.data.24.functionality"), 
  description: localize("interventions.data.24.description"), 
  target: 'phone', 
  level: 'medium',
  summary: localize("interventions.data.24.summary"),
  style: 'dialog'
}, {
  id: 25,
  shortname: 'TIME_NOTIFICATION',
  name: localize("interventions.data.25.name"), 
  icon: 'res://ic_moon', 
  functionality: localize("interventions.data.25.functionality"), 
  description: localize("interventions.data.25.description"), 
  target: 'phone', 
  level: 'medium',
  summary: localize("interventions.data.25.summary"),
  style: 'dialog'
}
];

exports.interventionIDs = {}
for (let intervention_info of exports.interventionDetails) {
  exports.interventionIDs[intervention_info.shortname] = intervention_info.id
}
